In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [24]:
import legendre

In [25]:
n_states = 2
X = np.array([-1, 1])
domain=[0, 1]
legendre.discretize(X, domain, n_states)

RuntimeError: X must be within the specified domain

In [26]:
n_states = 3
X = np.array([[0.25, 0.1],
              [0.5, 0.25]])
def P(x):
    x = 4 * x - 1
    polys = np.array((np.ones_like(x), x, (3.*x**2 - 1.) / 2.))
    tmp = (2. * np.arange(3)[:, None, None] + 1.) / 2. * polys
    return np.rollaxis(tmp, 0, 3)
domain = [0., 0.5]
print(legendre.discretize(X, domain, n_states))
print(P(X))
assert(np.allclose(legendre.discretize(X, domain, n_states), P(X)))

[[[ 0.5   0.   -1.25]
  [ 0.5  -0.9   0.1 ]]

 [[ 0.5   1.5   2.5 ]
  [ 0.5   0.   -1.25]]]
[[[ 0.5   0.   -1.25]
  [ 0.5  -0.9   0.1 ]]

 [[ 0.5   1.5   2.5 ]
  [ 0.5   0.   -1.25]]]


In [8]:
(2.*np.array(n_states)+1)/2.

3.5

In [ ]:
X_scaled = (2. * X - self.domain[0] - self.domain[1]) /\
           (self.domain[1] - self.domain[0])

In [13]:
n_states = 3
len(np.arange(n_states))

3